### ISSUE TITLE
The examples "Hello World" and "Hello Button" don't working | Windows 11 

### ISSUE THREAD

**Issue by Alihusejn** [mcorino/wxRuby3#272]
```
'>ruby test.rb'
<internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in 'require': cannot load such file -- wxruby_core (LoadError)
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in 'require'
        from C:/Users/User/.local/share/gem/ruby/3.2.0/gems/wxruby3-0.9.8/lib/wx/core.rb:9:in '<top (required)>'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in 'require'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in 'require'
        from C:/Users/User/.local/share/gem/ruby/3.2.0/gems/wxruby3-0.9.8/lib/wx.rb:9:in '<top (required)>'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:141:in 'require'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:141:in 'rescue in require'
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:135:in 'require'
        from test.rb:1:in '<main>'
<internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in 'require': cannot load such file -- wx (LoadError)
        from <internal:C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:136:in 'require'
        from test.rb:1:in '<main>'
```

**Comment by Alihusejn** [comment]
Alright, it works. I forgot to type `wxruby setup`. Sorry for the inconvenience.
