### ISSUE TITLE
problem loading Mac OS 14 after successful

### ISSUE THREAD

**Issue by tsurezuregusa** [mcorino/wxRuby3#340]
Thank you for developing this. I found it recently when I needed to build a quick GUI application, and it was very easy to learn quickly with the samples.
### Description
But on another machine running Mac OS Sonoma 14.4.1. It does not run for an unknown reason. Ruby and WX and prerequisites are installed with homebrew. I tried installing normally and with `--pre`.

#### Bug description:

Ruby cannot find wxruby. This happens with code I wrote and the samples. `wxruby test` returns 0.

#### Expected vs observed behaviour:

```
~ > wxruby sampler
/opt/homebrew/lib/ruby/gems/3.3.0/gems/wxruby3-1.3.1/samples/sampler/editor.rb:11:in `<top (required)>': undefined method `has_feature?' for module Wx (NoMethodError)

if Wx.has_feature?(:USE_STC)
     ^^^^^^^^^^^^^
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/wxruby3-1.3.1/samples/sampler.rb:15:in `require_relative'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/wxruby3-1.3.1/samples/sampler.rb:15:in `<main>'
```

#### To Reproduce:

```
~ > ruby --version
ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [arm64-darwin23]
~ > wx-config --version
3.2.6
~ > doxygen --version
1.12.0
~> swig --version

SWIG Version 4.3.0

Compiled with clang++ [aarch64-apple-darwin23.4.0]

Configured options: +pcre

Please see https://www.swig.org for reporting bugs and further information
~>  gem install wxruby3 --pre
Fetching wxruby3-1.3.1.gem
Building native extensions. This could take a while...

The wxRuby3 Gem has been successfully installed including the 'wxruby' utility.

In case no suitable binary release package was available for your platform you
will need to run the post-install setup process by executing:
~>  gem install wxruby3 --pre
Fetching wxruby3-1.3.1.gem
Building native extensions. This could take a while...

The wxRuby3 Gem has been successfully installed including the 'wxruby' utility.

In case no suitable binary release package was available for your platform you
will need to run the post-install setup process by executing:

$ wxruby setup

To check whether wxRuby3 is ready to run or not you can at any time execute the
following command:

$ wxruby check

Run 'wxruby check -h' for more information.

When the wxRuby3 setup has been fully completed you can start using wxRuby3.

You can run the regression tests to verify the installation by executing:

$ wxruby test

The wxRuby3 sample explorer can be run by executing:

$ wxruby sampler

Have fun using wxRuby3.

Run 'wxruby -h' to see information on the available commands.

Successfully installed wxruby3-1.3.1
Parsing documentation for wxruby3-1.3.1
Installing ri documentation for wxruby3-1.3.1
Done installing documentation for wxruby3 after 4 seconds
1 gem installed
~ > echo $PATH
/opt/homebrew/lib/ruby/gems/3.3.0/bin /opt/homebrew/opt/ruby/bin /opt/homebrew/bin /usr/local/bin /System/Cryptexes/App/usr/bin /usr/bin /bin /usr/sbin /sbin /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin /Library/TeX/texbin /Applications/iTerm.app/Contents/Resources/utilities
```
### Platform and version information

- wxRuby3 version 1.3.1
- wxRuby3 port WXOSX
- wxWidgets version 3.2.6
- OS (distribution)  Mac OS Sonoma 14.4.1

**Comment by mcorino** [comment]
Ok, no idea what went wrong here.
The Sonoma release builds on Cirrus CI were faultless and I can't see any obvious problem in your build sequence.

Unfortunately I only have MacOS Ventura available for direct testing so the only way to find the cause of this problem is you being willing to perform a number of tests.

First I would like to go some steps back.
You said you ran `wxruby test` and it returned `0`. Did you mean `wxruby check` (which is the correct command to check the installation) or did you actually run `wxruby test`? If the latter, did you also see test results being printed to the console? If the first, what was the output of the command if any? (in case of a successful 'check' there would not have been any output).
If you did not actually run `wxruby check` could you run `wxruby check -v` and report back on the command result?

**Comment by tsurezuregusa** [comment]
Thank you for replying.

It is the same problem with `test`.
```
~> wxruby -v check
Checking build (or binary package installation) completion...
Attempting to load wxRuby3 libraries...
~> wxruby test
/opt/homebrew/lib/ruby/gems/3.3.0/gems/wxruby3-1.3.1/tests/lib/wxapp_runner.rb:13:in `<module:Test>': uninitialized constant Wx::App (NameError)

    class App < Wx::App
                  ^^^^^
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/wxruby3-1.3.1/tests/lib/wxapp_runner.rb:11:in `<module:WxRuby>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/wxruby3-1.3.1/tests/lib/wxapp_runner.rb:9:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/wxruby3-1.3.1/tests/test_app_event_filter.rb:5:in `require_relative'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/wxruby3-1.3.1/tests/test_app_event_filter.rb:5:in `<main>'
```
I thought it might be related to the OS security system that changes so often, and the console gives this on `wxruby -v test`:
```
default	12:34:47.520623+0900	kernel	AMFI: '/opt/homebrew/Cellar/ruby/3.3.6/bin/ruby' is adhoc signed.
default	12:34:47.522829+0900	amfid	/opt/homebrew/Cellar/ruby/3.3.6/bin/ruby not valid: Error Domain=AppleMobileFileIntegrityError Code=-423 "The file is adhoc signed or signed by an unknown certificate chain" UserInfo={NSURL=file:///opt/homebrew/Cellar/ruby/3.3.6/bin/ruby, NSLocalizedDescription=The file is adhoc signed or signed by an unknown certificate chain}
default	12:34:47.536899+0900	kernel	AMFI: '/opt/homebrew/Cellar/ruby/3.3.6/lib/libruby.3.3.dylib' is adhoc signed.
default	12:34:47.541131+0900	amfid	/opt/homebrew/Cellar/ruby/3.3.6/lib/libruby.3.3.dylib not valid: Error Domain=AppleMobileFileIntegrityError Code=-423 "The file is adhoc signed or signed by an unknown certificate chain" UserInfo={NSURL=file:///opt/homebrew/Cellar/ruby/3.3.6/lib/libruby.3.3.dylib, NSLocalizedDescription=The file is adhoc signed or signed by an unknown certificate chain}
default	12:34:47.558140+0900	kernel	AMFI: '/opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/arm64-darwin23/enc/encdb.bundle' is adhoc signed.
default	12:34:47.559248+0900	amfid	/opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/arm64-darwin23/enc/encdb.bundle not valid: Error Domain=AppleMobileFileIntegrityError Code=-423 "The file is adhoc signed or signed by an unknown certificate chain" UserInfo={NSURL=file:///opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/arm64-darwin23/enc/encdb.bundle, NSLocalizedDescription=The file is adhoc signed or signed by an unknown certificate chain}
default	12:34:47.563360+0900	kernel	AMFI: '/opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/arm64-darwin23/enc/trans/transdb.bundle' is adhoc signed.
default	12:34:47.564534+0900	amfid	/opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/arm64-darwin23/enc/trans/transdb.bundle not valid: Error Domain=AppleMobileFileIntegrityError Code=-423 "The file is adhoc signed or signed by an unknown certificate chain" UserInfo={NSURL=file:///opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/arm64-darwin23/enc/trans/transdb.bundle, NSLocalizedDescription=The file is adhoc signed or signed by an unknown certificate chain}
default	12:34:47.599302+0900	kernel	AMFI: '/opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/arm64-darwin23/monitor.bundle' is adhoc signed.
default	12:34:47.600306+0900	amfid	/opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/arm64-darwin23/monitor.bundle not valid: Error Domain=AppleMobileFileIntegrityError Code=-423 "The file is adhoc signed or signed by an unknown certificate chain" UserInfo={NSURL=file:///opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/arm64-darwin23/monitor.bundle, NSLocalizedDescription=The file is adhoc signed or signed by an unknown certificate chain}
default	12:34:47.724656+0900	kernel	AMFI: '/opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/arm64-darwin23/io/console.bundle' is adhoc signed.
default	12:34:47.725745+0900	amfid	/opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/arm64-darwin23/io/console.bundle not valid: Error Domain=AppleMobileFileIntegrityError Code=-423 "The file is adhoc signed or signed by an unknown certificate chain" UserInfo={NSURL=file:///opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/arm64-darwin23/io/console.bundle, NSLocalizedDescription=The file is adhoc signed or signed by an unknown certificate chain}
default	12:34:47.732566+0900	kernel	AMFI: '/opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/arm64-darwin23/ripper.bundle' is adhoc signed.
default	12:34:47.733572+0900	amfid	/opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/arm64-darwin23/ripper.bundle not valid: Error Domain=AppleMobileFileIntegrityError Code=-423 "The file is adhoc signed or signed by an unknown certificate chain" UserInfo={NSURL=file:///opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/arm64-darwin23/ripper.bundle, NSLocalizedDescription=The file is adhoc signed or signed by an unknown certificate chain}
error	12:34:47.758429+0900	kernel	Sandbox: logd_helper(75131) deny(1) file-read-data /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/arm64-darwin23/enc/encdb.bundle
error	12:34:47.759046+0900	kernel	Sandbox: logd_helper(75131) deny(1) file-read-data /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/arm64-darwin23/enc/trans/transdb.bundle
error	12:34:47.765719+0900	kernel	Sandbox: logd_helper(75131) deny(1) file-read-data /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/arm64-darwin23/monitor.bundle

```

Unfortunately I do not know how to resolve the problem. The terminal applications have Full Disk　Access in security preferences. I added the homebrew ruby binary, but the problem persists.

I had not looked at the syslog but similar error appear when running ruby scripts that do function correctly.

**Comment by mcorino** [comment]
Hmmm, extremely weird. `wxruby check` seems to have no problems which should indicate that `require 'wx'` does not encounter problems (i.e. the native extension libraries seem to be loaded). But on the other hand test or sample code run into problems as soon as they reference anything from the `Wx` namespace as if nothing gets loaded after all.

As said I only can test locally on MacOS Ventura and there I see none of the syslog messages you see using Homebrew installed Ruby (neither when using RVM installed Ruby). And unfortunately I am far from being a MacOS expert (nor do I aspire to be one) so I have no idea what these messages are about and whether they are harmful. As you note other Ruby scripts to emit these messages as well despite running successfully I would assume them to be essentially harmless.

Let's back up entirely to the beginning.
Your initial message notes having installed wxWidgets as a prerequisite (I missed that earlier). Why did you do that? When installing wxRuby3 for any of the supported platforms (which includes MacOS Sonoma ARM64) the installed binary package will include the required wxWidgets libraries. Only when you explicitly have a need to share the wxWidgets libraries with other (non-wxRuby) apps or want to use a customized wxWidgets installation would you have use for a user installed wxWidgets. If you have no such need I would remove this wxWidgets installation to exclude the possibility of this causing any issues.

To verify the wxRuby3 gem installation I would like you execute the following commands:

- `ls -l /opt/homebrew/lib/ruby/gems/3.3.0/gems/wxruby3-1.3.1/`
- `ls -l /opt/homebrew/lib/ruby/gems/3.3.0/gems/wxruby3-1.3.1/lib`
- `ls -l /opt/homebrew/lib/ruby/gems/3.3.0/gems/wxruby3-1.3.1/ext`

and report back the output (please use attachments and not inline texts).

Additionally could you run the command `ruby -v -r wx -e "p Wx; p Wx::WXRUBY_VERSION"` and report back the output of that.

**Comment by tsurezuregusa** [comment]
Thank you again. I thought I installed wxWidgets because wxRuby3 did not work when installed normally `gem install --user wxruby3`. But it was already installed as prerequisite for another package. Maybe what I did was to update. Uninstalling that and reinstalling this did not help the problem.

With Mac OS security, I am not extremely familiar, because my normal machine is not updated and the system changes rapidly. I think the syslog errors are related to increasing security.

```
~>  ruby -v -r wx -e "p Wx; p Wx::WXRUBY_VERSION"
ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [arm64-darwin23]
Wx
-e:1:in `<main>': uninitialized constant Wx::WXRUBY_VERSION (NameError)

p Wx; p Wx::WXRUBY_VERSION
          ^^^^^^^^^^^^^^^^
```
[ls.txt](https://github.com/user-attachments/files/18249370/ls.txt)

**Comment by mcorino** [comment]
Ok, this is still very weird.

`ls.txt` seems to indicate the gem installation is complete.

And although the output of `ruby -v -r wx -e "p Wx; p Wx::WXRUBY_VERSION"` shows no error for the require of the `wx` main loader file and clearly shows the `Wx` module exists it also shows that loading the members of the `Wx` namespace did not succeed. As the `Wx::WXRUBY_VERSION` constant is defined fairly early on in the core loading process this is very weird.
Also, if loading the core members was successful the output should have contained a long list of method redefinition warnings.

Ok, let's back up even more. What is the output of the following command:

`ruby -v -r "wx/core" -e "\$LOADED_FEATURES.each {|s| puts s if s =~ /\\/wx/}"`

**Comment by tsurezuregusa** [comment]
This looks interesting. Hopefully it helps you understand.
[out.txt](https://github.com/user-attachments/files/18256726/out.txt)

**Comment by mcorino** [comment]
Huh, this is odd. It seems that now the library is actually loaded.
The method redefinition warnings are those that I expected to see for requiring the toplevel `wx` loader as well. 

Can you repeat this with command `ruby -v -r "wx" -e "\$LOADED_FEATURES.each {|s| puts s if s =~ /\\/wx/}"` as well.
We need to see what 'wx' file is loaded and if that loads the rest as well.

**Comment by mcorino** [comment]
> Huh, this is odd. It seems that now the library is actually loaded. The method redefinition warnings are those that I expected to see for requiring the toplevel `wx` loader as well.
> 
> Can you repeat this with command `ruby -v -r "wx" -e "\$LOADED_FEATURES.each {|s| puts s if s =~ /\\/wx/}"` as well. We need to see what 'wx' file is loaded and if that loads the rest as well.

Have you been able to run this test?

**Comment by tsurezuregusa** [comment]
I was able to solve the problem with this last command which looked strange:

```
~> ruby -v -r "wx" -e "\$LOADED_FEATURES.each {|s| puts s if s =~ /\\/wx/}"
ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [arm64-darwin23]
/Users/user/.gem/ruby/3.3.0/gems/wx-0.0.0/lib/wx/version.rb
/Users/user/.gem/ruby/3.3.0/gems/wx-0.0.0/lib/wx.rb
```

After `gem uninstall wx` I reinstalled wxruby and now it functions. I tried installing to the system location and to the user directory, but both work now. I do not know how `wx-0.0.0` was installed.

[output.txt](https://github.com/user-attachments/files/18341308/output.txt)

Thank you for the assistance.
